2019-12-03 14:57:03,323 ERROR: Exception on /index [POST] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/routes.py", line 22, in index
    form = WorkoutForm()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 668, in __init__
    super(FloatField, self).__init__(label, validators, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'Name'
2019-12-03 14:57:37,839 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:49]
2019-12-10 10:31:12,597 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:49]
2019-12-10 13:36:09,001 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-10 13:48:28,570 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-10 13:50:36,378 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-10 13:50:40,699 ERROR: Exception on /auth/login [GET] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/repos/mytrilog/app/auth/routes.py", line 27, in login
    return render_template('auth/login.html', title='S I G N  in', form=form)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/scratch/knerr/repos/mytrilog/app/templates/auth/login.html", line 4, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/scratch/knerr/repos/mytrilog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/scratch/knerr/repos/mytrilog/app/templates/base.html", line 21, in block "navbar"
    <a href="{{url_for('index')}}">Home</a>  |
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2019-12-10 14:00:45,229 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-10 14:17:18,354 ERROR: Exception on /auth/reset_password_request [POST] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/repos/mytrilog/app/auth/routes.py", line 58, in reset_password_request
    send_password_reset_email(user)
  File "/scratch/knerr/repos/mytrilog/app/auth/email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/scratch/knerr/repos/mytrilog/app/models.py", line 65, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'app' is not defined
2019-12-10 14:21:03,064 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
