2019-12-10 14:21:08,582 ERROR: Exception on /auth/reset_password_request [POST] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/repos/mytrilog/app/auth/routes.py", line 58, in reset_password_request
    send_password_reset_email(user)
  File "/scratch/knerr/repos/mytrilog/app/auth/email.py", line 9, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-12-10 14:21:51,532 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 10:34:12,055 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 10:55:52,914 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 11:02:33,040 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 11:06:19,368 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 11:51:29,471 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 11:51:45,116 ERROR: Exception on /index [POST] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/scratch/knerr/repos/mytrilog/app/main/routes.py", line 33, in index
    workouts = user.workouts
AttributeError: 'function' object has no attribute 'workouts'
2019-12-11 11:53:47,522 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 11:54:41,182 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 11:59:50,726 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 12:03:27,583 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
2019-12-11 12:08:36,191 INFO: MyTriLog startup... [in /scratch/knerr/repos/mytrilog/app/__init__.py:62]
